-- Inserindo os 200 alunos e suas matrículas em cursos aleatórios
INSERT INTO Aluno (idAluno, nome, sobrenome, curso) VALUES
(1, 'João', 'Silva', 'Administração'),
(2, 'Maria', 'Souza', 'Engenharia Civil'),
(3, 'José', 'Oliveira', 'Engenharia de Computação'),
(4, 'Ana', 'Santos', 'Engenharia Elétrica'),
(5, 'Pedro', 'Pereira', 'Engenharia Mecânica'),
(6, 'Carlos', 'Lima', 'Direito'),
(7, 'Paula', 'Carvalho', 'Medicina'),
(8, 'Fernando', 'Almeida', 'Enfermagem'),
(9, 'Mariana', 'Rodrigues', 'Psicologia'),
(10, 'Lucas', 'Martins', 'Ciências Contábeis'),
(11, 'Gabriela', 'Barbosa', 'Economia'),
(12, 'Roberto', 'Ribeiro', 'Arquitetura e Urbanismo'),
(13, 'Cláudia', 'Monteiro', 'Design'),
(14, 'André', 'Cardoso', 'Jornalismo'),
(15, 'Alice', 'Alves', 'Publicidade e Propaganda'),
(16, 'Ricardo', 'Castro', 'Relações Internacionais'),
(17, 'Sofia', 'Freitas', 'Biologia'),
(18, 'Luis', 'Mendes', 'Física'),
(19, 'Beatriz', 'Teixeira', 'Química'),
(20, 'Bruno', 'Fernandes', 'Matemática'),
(21, 'Juliana', 'Ferreira', 'História'),
(22, 'Gustavo', 'Gonçalves', 'Geografia'),
(23, 'Laura', 'Lopes', 'Letras'),
(24, 'Marcelo', 'Costa', 'Educação Física'),
(25, 'Isabela', 'Araújo', 'Farmácia'),
(26, 'Rafael', 'Moreira', 'Administração'),
(27, 'Amanda', 'Correia', 'Engenharia Civil'),
(28, 'Tiago', 'Reis', 'Engenharia de Computação'),
(29, 'Vanessa', 'Nunes', 'Engenharia Elétrica'),
(30, 'Fábio', 'Rocha', 'Engenharia Mecânica'),
(31, 'Sandra', 'Peixoto', 'Direito'),
(32, 'Renato', 'Torres', 'Medicina'),
(33, 'Patrícia', 'Souza', 'Enfermagem'),
(34, 'Diego', 'Andrade', 'Psicologia'),
(35, 'Marina', 'Barros', 'Ciências Contábeis'),
(36, 'Antônio', 'Amaral', 'Economia'),
(37, 'Raquel', 'Santana', 'Arquitetura e Urbanismo'),
(38, 'Vitor', 'Farias', 'Design'),
(39, 'Daniela', 'Neves', 'Jornalismo'),
(40, 'Alexandre', 'Silveira', 'Publicidade e Propaganda'),
(41, 'Carolina', 'Tavares', 'Relações Internacionais'),
(42, 'Leonardo', 'Barros', 'Biologia'),
(43, 'Luana', 'Pinto', 'Física'),
(44, 'Felipe', 'Gomes', 'Química'),
(45, 'Camila', 'Miranda', 'Matemática'),
(46, 'Rodrigo', 'Ramalho', 'História'),
(47, 'Tatiana', 'Ramos', 'Geografia'),
(48, 'Sérgio', 'Leite', 'Letras'),
(49, 'Adriana', 'Monteiro', 'Educação Física'),
(50, 'Matheus', 'Albuquerque', 'Farmácia'),
(51, 'Luciana', 'Bezerra', 'Administração'),
(52, 'Victor', 'Azevedo', 'Engenharia Civil'),
(53, 'Lorena', 'Cardoso', 'Engenharia de Computação'),
(54, 'Igor', 'Pacheco', 'Engenharia Elétrica'),
(55, 'Renata', 'Borges', 'Engenharia Mecânica'),
(56, 'Henrique', 'Ferreira', 'Direito'),
(57, 'Clara', 'Magalhães', 'Medicina'),
(58, 'Fernanda', 'Rezende', 'Enfermagem'),
(59, 'Samuel', 'Marques', 'Psicologia'),
(60, 'Diana', 'Rezende', 'Ciências Contábeis'),
(61, 'Paulo', 'Barros', 'Economia'),
(62, 'Helena', 'Passos', 'Arquitetura e Urbanismo'),
(63, 'Murilo', 'Ferraz', 'Design'),
(64, 'Bruna', 'Bernardo', 'Jornalismo'),
(65, 'Rui', 'Ramos', 'Publicidade e Propaganda'),
(66, 'Elaine', 'Abreu', 'Relações Internacionais'),
(67, 'Caio', 'Campos', 'Biologia'),
(68, 'Elisa', 'Arruda', 'Física'),
(69, 'Mário', 'Machado', 'Química'),
(70, 'Júlia', 'Rosa', 'Matemática'),
(71, 'Renan', 'Braga', 'História'),
(72, 'Marcela', 'Melo', 'Geografia'),
(73, 'Thiago', 'Barros', 'Letras'),
(74, 'Aline', 'Queiroz', 'Educação Física'),
(75, 'Eduardo', 'Mattos', 'Farmácia'),
(76, 'Denise', 'Nogueira', 'Administração'),
(77, 'Cristiano', 'Guimarães', 'Engenharia Civil'),
(78, 'Letícia', 'Batista', 'Engenharia de Computação'),
(79, 'Francisco', 'Rios', 'Engenharia Elétrica'),
(80, 'Priscila', 'Garcia', 'Engenharia Mecânica'),
(81, 'Emanuel', 'Rosa', 'Direito'),
(82, 'Aurora', 'Paiva', 'Medicina'),
(83, 'Augusto', 'Vieira', 'Direito'),
(84, 'Ligia', 'Prado', 'Enfermagem'),
(85, 'Edson', 'Bueno', 'Psicologia'),
(86, 'Melissa', 'Henriques', 'Ciências Contábeis'),
(87, 'Romeu', 'Coutinho', 'Economia'),
(88, 'Regina', 'Franco', 'Arquitetura e Urbanismo'),
(89, 'Guilherme', 'Paula', 'Design'),
(90, 'Tereza', 'Botelho', 'Jornalismo'),
(91, 'Vinícius', 'Lins', 'Publicidade e Propaganda'),
(92, 'Andréa', 'Veloso', 'Relações Internacionais'),
(93, 'Miguel', 'Pinto', 'Biologia'),
(94, 'Sara', 'Lima', 'Física'),
(95, 'Nilson', 'Pires', 'Química'),
(96, 'Julio', 'Simões', 'Matemática'),
(97, 'Estela', 'Macedo', 'História'),
(98, 'Sandro', 'Rabelo', 'Geografia'),
(99, 'Márcia', 'Frota', 'Letras'),
(100, 'Lucas', 'Cavalcante', 'Educação Física'),
(101, 'Betina', 'Medeiros', 'Farmácia'),
(102, 'Otávio', 'Coelho', 'Administração'),
(103, 'Valentina', 'Medeiros', 'Engenharia Civil'),
(104, 'Danilo', 'Cavalcanti', 'Engenharia de Computação'),
(105, 'Ivana', 'Freire', 'Engenharia Elétrica'),
(106, 'Enzo', 'Aguiar', 'Engenharia Mecânica'),
(107, 'Marta', 'Carneiro', 'Direito'),
(108, 'Rafael', 'Soares', 'Medicina'),
(109, 'Teresa', 'Vianna', 'Enfermagem'),
(110, 'Brenda', 'Roriz', 'Psicologia'),
(111, 'Nelson', 'Cavalcante', 'Ciências Contábeis'),
(112, 'Adriano', 'Soares', 'Economia'),
(113, 'Sônia', 'Rezende', 'Arquitetura e Urbanismo'),
(114, 'Nicolas', 'Pedrosa', 'Design'),
(115, 'Suzana', 'Valente', 'Jornalismo'),
(116, 'Alessandro', 'Rangel', 'Publicidade e Propaganda'),
(117, 'Íris', 'Fialho', 'Relações Internacionais'),
(118, 'Arnaldo', 'Machado', 'Biologia'),
(119, 'Irene', 'Guimarães', 'Física'),
(120, 'Clovis', 'Castelo', 'Química'),
(121, 'Mirian', 'Meireles', 'Matemática'),
(122, 'Evandro', 'Portela', 'História'),
(123, 'Jaqueline', 'Vieira', 'Geografia'),
(124, 'Lucio', 'Sampaio', 'Letras'),
(125, 'Dina', 'Mariano', 'Educação Física'),
(126, 'Geraldo', 'Camargo', 'Farmácia'),
(127, 'Luiza', 'Arantes', 'Administração'),
(128, 'Nelson', 'Bastos', 'Engenharia Civil'),
(129, 'Naiara', 'Souza', 'Engenharia de Computação'),
(130, 'Alvaro', 'Ávila', 'Engenharia Elétrica'),
(131, 'Bianca', 'Esteves', 'Engenharia Mecânica'),
(132, 'Clemente', 'Marinho', 'Direito'),
(133, 'Maíra', 'Vasconcelos', 'Medicina'),
(134, 'Elias', 'Antunes', 'Enfermagem'),
(135, 'Laila', 'Abreu', 'Psicologia'),
(136, 'Juliano', 'Guimarães', 'Ciências Contábeis'),
(137, 'Melissa', 'Campos', 'Economia'),
(138, 'Humberto', 'Esteves', 'Arquitetura e Urbanismo'),
(139, 'Daniele', 'Luz', 'Design'),
(140, 'Robson', 'Castro', 'Jornalismo'),
(141, 'Ilana', 'Pinto', 'Publicidade e Propaganda'),
(142, 'Cezar', 'Alves', 'Relações Internacionais'),
(143, 'Nádia', 'Pontes', 'Biologia'),
(144, 'Flávio', 'Braga', 'Física'),
(145, 'Mônica', 'Lins', 'Química'),
(146, 'Orlando', 'Fernandes', 'Matemática'),
(147, 'Sabrina', 'Sales', 'História'),
(148, 'Saulo', 'Miranda', 'Geografia'),
(149, 'Neuza', 'Caldeira', 'Letras'),
(150, 'Felício', 'Silveira', 'Educação Física'),
(151, 'Antônia', 'Martins', 'Farmácia'),
(152, 'Alfredo', 'Menezes', 'Administração'),
(153, 'Daniela', 'Neves', 'Engenharia Civil'),
(154, 'Luciano', 'Gusmão', 'Engenharia de Computação'),
(155, 'Ana', 'Amaral', 'Engenharia Elétrica'),
(156, 'Rodolfo', 'Araújo', 'Engenharia Mecânica'),
(157, 'Debora', 'Reis', 'Direito'),
(158, 'Alberto', 'Melo', 'Medicina'),
(159, 'Amália', 'Souza', 'Enfermagem'),
(160, 'Maurício', 'Rezende', 'Psicologia'),
(161, 'Vera', 'Lopes', 'Ciências Contábeis'),
(162, 'Jonas', 'Ribeiro', 'Economia'),
(163, 'Edna', 'Barros', 'Arquitetura e Urbanismo'),
(164, 'Nivaldo', 'Rocha', 'Design'),
(165, 'Rosa', 'Gomes', 'Jornalismo'),
(166, 'Senivaldo', 'Santos', 'Engenharia Civil'),
(167, 'Regina', 'Santana', 'Publicidade e Propaganda'),
(168, 'Darlan', 'Correia', 'Relações Internacionais'),
(169, 'Inês', 'Medeiros', 'Biologia'),
(170, 'Celso', 'Pinto', 'Física'),
(171, 'Rafaela', 'Alves', 'Química'),
(172, 'Eber', 'Costa', 'Matemática'),
(173, 'Janaína', 'Lima', 'História'),
(174, 'Hélio', 'Carvalho', 'Geografia'),
(175, 'Glória', 'Rodrigues', 'Letras'),
(176, 'Haroldo', 'Pereira', 'Educação Física'),
(177, 'Susana', 'Oliveira', 'Farmácia'),
(178, 'Eunice', 'Silva', 'Administração'),
(179, 'Edmilson', 'Lima', 'Engenharia Civil'),
(180, 'Paloma', 'Souza', 'Engenharia de Computação'),
(181, 'João', 'Almeida', 'Engenharia Elétrica'),
(182, 'Selma', 'Gonçalves', 'Engenharia Mecânica'),
(183, 'Ronaldo', 'Martins', 'Direito'),
(184, 'Reginaldo', 'Rocha', 'Medicina'),
(185, 'Marina', 'Santos', 'Enfermagem'),
(186, 'Carla', 'Ferreira', 'Psicologia'),
(187, 'Gabriel', 'Santana', 'Ciências Contábeis'),
(188, 'Márcio', 'Albuquerque', 'Economia'),
(189, 'Fernanda', 'Oliveira', 'Arquitetura e Urbanismo'),
(190, 'César', 'Lima', 'Design'),
(191, 'Nicolas', 'Pedrosa', 'Jornalismo'),
(192, 'Suzana', 'Valente', 'Publicidade e Propaganda'),
(193, 'Alessandro', 'Rangel', 'Relações Internacionais'),
(194, 'Íris', 'Fialho', 'Biologia'),
(195, 'Arnaldo', 'Machado', 'Física'),
(196, 'Irene', 'Guimarães', 'Química'),
(197, 'Clovis', 'Castelo', 'Matemática'),
(198, 'Mirian', 'Meireles', 'História'),
(199, 'Evandro', 'Portela', 'Geografia'),
(200, 'Jaqueline', 'Vieira', 'Letras');




SET SQL_SAFE_UPDATES = 0;
UPDATE Alunos SET email = CONCAT(nome, '.', sobrenome, '@dominio.com');

DELIMITER $
CREATE TRIGGER gerarEmailAluno
BEFORE INSERT ON Alunos
FOR EACH ROW
BEGIN
	SET NEW.email = CONCAT(NEW.nome, '.', NEW.sobrenome, '@dominio.com');
END;
$
DELIMITER ;    
-- testando a trigger criada
INSERT INTO Alunos (nome, sobrenome) VALUES ('Guilherme', 'Souza');

DELIMITER $
CREATE PROCEDURE matricularAluno(
IN idAluno INT,
IN nome VARCHAR(20),
IN sobrenome VARCHAR(20),
IN curso VARCHAR(30),
IN area VARCHAR(30)
)
BEGIN
	DECLARE v_idCurso INT;	
        
	INSERT INTO Alunos (idAluno, nome, sobrenome, email, curso)
	VALUES (idAluno, nome, sobrenome, email, curso);
	SELECT 'Matrícula feita com sucesso!' AS mensagem;
END;
$
DELIMITER ;     
-- testando a procedure criada
CALL matricularAluno(201,'Fernando', 'Santos', 'Pedagogia', 'Humanas');
CALL matricularAluno(202,'Sabrina', 'Juliana', 'Psicologia', 'Humanas');